import Population from "@src/components/population/population";
import type { Meta, StoryObj } from "@storybook/react";

const meta: Meta<typeof Population> = {
  component: Population,
  parameters: {
    layout: "fullscreen",
  },
};

type Story = StoryObj<typeof Population>;

export const Basic: Story = {
  args: {
    countries: [
      {
        name: "United States",
        code: "US",
        emoji: "🇺🇸",
        image:
          "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
        unicode: "U+1F1FA U+1F1F8",
      },
    ],
    transformedData: [
      {
        country_id: "US",
        country_value: "United States",
        date: "1973",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 1425376000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1974",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 1545243000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1975",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 1684904000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1976",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 1873412000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1977",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 2081826000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1978",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 2351599000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1979",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 2627333000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1980",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 2857307000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1981",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 3207041000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1982",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 3343789000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1983",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 3634038000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1984",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 4037613000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1985",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 4338979000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1986",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 4579631000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1987",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 4855215000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1988",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 5236438000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1989",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 5641580000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1990",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 5963144000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1991",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 6158129000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1992",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 6520327000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1993",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 6858559000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1994",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 7287236000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1995",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 7639749000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1996",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 8073122000000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1997",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 8577554457000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1998",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 9062818202000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "1999",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 9631174489000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2000",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 10250947997000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2001",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 10581929774000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2002",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 10929112955000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2003",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 11456442041000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2004",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 12217193198000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2005",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 13039199193000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2006",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 13815586948000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2007",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 14474226905000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2008",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 14769857911000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2009",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 14478064934000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2010",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 15048964444000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2011",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 15599728123000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2012",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 16253972230000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2013",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 16843190993000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2014",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 17550680174000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2015",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 18206020741000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2016",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 18695110842000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2017",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 19477336549000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2018",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 20533057312000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2019",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 21380976119000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2020",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 21060473613000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2021",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 23315080560000,
      },
      {
        country_id: "US",
        country_value: "United States",
        date: "2022",
        indicator_id: "NY.GDP.MKTP.CD",
        indicator_value: "GDP (current US$)",
        value: 25462700000000,
      },
    ],
  },
};

export default meta;
