import "./globals.css";
import type { Metadata } from "next";
import classNames from "classnames";
import Header from "@src/components/Header";
import { Inter, Noto_Sans_JP } from "next/font/google";

export const metadata: Metadata = {
  title: "国会発言分析",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const notoSansJP = Noto_Sans_JP({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={classNames(inter.variable, notoSansJP.variable)}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
